# typed: false
# frozen_string_literal: true

# Generated by the d9c release workflow (cmd/distgen) — do not edit by hand.
class D9c < Formula
  desc "Terminal UI for managing Docker on remote hosts over TCP or SSH"
  homepage "https://github.com/kirg0/d9c"
  version "1.30.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kirg0/d9c/releases/download/v1.30.0/d9c_v1.30.0_darwin_amd64.tar.gz"
      sha256 "d2b87ed506c83f2c2d69b48629abc4e52946d9b44366817d9ac665511163044a"
    end
    on_arm do
      url "https://github.com/kirg0/d9c/releases/download/v1.30.0/d9c_v1.30.0_darwin_arm64.tar.gz"
      sha256 "4cec3e3d14e72ac364aeaf4adf4de2860faebab55d94353f80865529fe826199"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kirg0/d9c/releases/download/v1.30.0/d9c_v1.30.0_linux_amd64.tar.gz"
      sha256 "761847f637730c92821d91e74863db2d8ff70b57b79178581f2aebd107d4e6b1"
    end
    on_arm do
      url "https://github.com/kirg0/d9c/releases/download/v1.30.0/d9c_v1.30.0_linux_arm64.tar.gz"
      sha256 "6c87008b0022d1cda86173764e93352daca6dcf4b0c6e31e91649d0754724a0e"
    end
  end

  def install
    bin.install "d9c"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/d9c -version")
  end
end
