# typed: false
# frozen_string_literal: true

# Generated by the d9c release workflow (cmd/distgen) — do not edit by hand.
class D9c < Formula
  desc "Terminal UI for managing Docker on remote hosts over TCP or SSH"
  homepage "https://github.com/kirg0/d9c"
  version "1.29.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kirg0/d9c/releases/download/v1.29.0/d9c_v1.29.0_darwin_amd64.tar.gz"
      sha256 "07a472d3c2e1230790095c3b6598a8544775a5008c3852e0b8b58e50e34f968b"
    end
    on_arm do
      url "https://github.com/kirg0/d9c/releases/download/v1.29.0/d9c_v1.29.0_darwin_arm64.tar.gz"
      sha256 "58c7813917e1ef9e5e5f91d2196b178ffdd47cd2dfc634a11360bcb0f3226ba5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kirg0/d9c/releases/download/v1.29.0/d9c_v1.29.0_linux_amd64.tar.gz"
      sha256 "e108e75a191b40458706208c77ea55352f2764b8a0b8b2dd744ae2ada98dcb26"
    end
    on_arm do
      url "https://github.com/kirg0/d9c/releases/download/v1.29.0/d9c_v1.29.0_linux_arm64.tar.gz"
      sha256 "bcfeb5fdd99dab30b2d47acb8c4a816312116c60f32a8710b3770a5c78833bd3"
    end
  end

  def install
    bin.install "d9c"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/d9c -version")
  end
end
